### PR TITLE
Update docker to build locally.

### PR DESCRIPTION
**Pull request by brianpeiris**
Also Update README.

This is a prerequisite for #11

### CODE REVIEW

**Comment by pierreozoux** [comment]
same as #11

**Comment by brianpeiris** [comment]
Can you reconsider merging this PR please? It actually has little to do with SSL, I just updated things so that people could actually build the docker locally.

**Comment by pierreozoux** [comment]
@brianpeiris  could you update the compose to version >2 then it will support both tags `build`and `image` thanks!

**Comment by brianpeiris** [comment]
Ah. I'll try when I have some time. Thanks.

**Comment by brianpeiris** [comment]
Gonna close this for now at least. I've stopped running my own server for the time being.

**Pull request closed without merging**
